version: 2
updates:
  # Update GitHub actions
  - directory: /
    open-pull-requests-limit: 5
    package-ecosystem: github-actions
    schedule:
      interval: weekly
      day: saturday
  # Update Python dependencies
  - directory: /
    open-pull-requests-limit: 5
    package-ecosystem: pip
    schedule:
      interval: weekly
      day: saturday
