name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  pylint:
    name: Pylint Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install poetry
        uses: snok/install-poetry@v1
      - name: Install project
        run: poetry install --only main,pre-commit
      - name: Run pylint
        run: pylint **/*.py

  unit-tests:
    name: Unit Tests - Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        uses: snok/install-poetry@v1
      - name: Install project
        run: poetry install --only main,testing
      - name: Run Pytest
        run: poetry run pytest tests
