name: Run Tests
on:
  - push
  - pull_request

jobs:
  run-tests:
    name: Python ${{ matrix.python-version }} Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]
    container:
      image: python:${{ matrix.python-version }}-buster
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | \
          python - \
          && echo "PATH=$HOME/.poetry/bin:$PATH" >> $GITHUB_ENV
      - name: Install Library
        run: poetry install --no-interaction --no-ansi
      - name: Fix Disutils
        run: poetry run pip install setuptools==59.5.0
      - name: Run Pytest
        run: poetry run pytest tests
